###
GET http://localhost:8000/api/jugadores/643f73b4834993e9646c25cd

###
GET http://localhost:8000/api/jugadores

###
POST http://localhost:8000/api/jugadores
Content-Type: application/json

{
    "nombre": "Juan",
    "goles": 5,
    "fecha_vinculacion": "12/04/2003"
}

###
DELETE http://localhost:8000/api/jugadores/643f73b4834993e9646c25cd