name: Build and Deploy on Firebase
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install
      working-directory: frontend
    - name: Build
      run: npm run build
      working-directory: frontend
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: frontend/dist
          working-directory: frontend
      - name: Deploy to Firebase 
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
         entryPoint: frontend/firebase.json
         repoToken: ${{ secrets.GITHUB_TOKEN }}
         firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
         projectId: "datos-milagroso"
         channelId: live

