name: Despliegue en Firebase

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 18.16.0
    - name: Install dependencies
      run: npm install
    - name: Build
      run: ng build  
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --project ${{ secrets.MY_FIREBASE_PROJECT }} --token ${{ secrets.MY_FIREBASE_TOKEN }}
