name: Despliegue en Firebase

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 18.16.0
    - name: Install dependencies
      run: npm install
    - name: Build
      run: ng build  
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --project ${{ datos-milagroso}} --token ${{ MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCg3G1cgDWSz5u2\nYmZRo8SU/VFzYbVR13FrRvIcB9lS6vsK5ED1imFUvIyHopRH3AUbyXsjDykwCt6M\ny6d0kq1P7yTijsVNDK0Haiottv5OoUOPv2BYOkVlreBS0dnVL9BrASj1CB+ExgdL\niduId8UEMlzqIeHrxRyjEtbSrASZULGVARsRXBLrkOSHMq/jYu09onZ/BbjdNUUQ\n6X9zihOKzx+J3pkgpxJ8EVo9Ga9yzJvL4ai5esc7TQXM5ICe9wjSmGvw4gdvqz0H\nLMQiw2tYBr4aYEx21ZYIZCGrt+V0Abgd0wX8glaeUpeKwnTb09xBHdd6V9xO/SDr\nKaQMBddRAgMBAAECggEAScL55M4ngsPvF3FEkNADLvx/smRN9BLR/8qe70qMFVEJ\nv4NN5CnJmsUAvZtH2jGiKA06CSgFD3IUfcRO643sqfgzVi34e+3Bk+JTJ/Y+44hg\nBhTP1XUW6FqUP/XZKMANlluIT9+jMEtsAe/belbNQTDk2TmjMm0GxiI33o+hZjlX\nfMRdQS2nO34hSRAlmqa2NpTfOzYszD2IWV0h/kKo1SPBZexD7xfLH3iBVfClULx8\nkSmChlkcguwn63pp83pDNzbYhFw/SxYg08hFVRQ8uHyP3a+vzD93XhAU6gWKXyK4\nq61Wkba8hVzSKD1y4XrVQzJROoG7uOVi57C9c7ndNwKBgQDUtHkO6rxnU/qPpcNd\nRLec5RcmLaNkFOn0dLymggODmNU67qatlBl07M2yPAFTKs5TzCYD3clFi3+9sifM\npOTpiCAfUXo1Lc5pzGQGqZXimbfXPVwfA0vhMwVRxGcHdZql9H2NVeqN40U7ee07\nSEy5vunntt3JS/FODoj7tW7bmwKBgQDBmn8CSS0nbn+Xvx8/7Ea1hA2C0xqChjqS\nEq3aCxSZI3xzTlPBl2H+WwA7efRanef6B7s83OxVb53B0qhQaTz2D3+mI8i3UGM+\nGPw+RwtverBEhSqrYks2TyDzDzWam/jvJ5mpVbE/sHkp6mQuO/ZU6vYF8qMCTA4L\nZC4oCLNVgwKBgB2kTN6MTdckd91+3zvnMKNXtaMnZwayd2wOvJ+DrNOw/74nteio\no+eMfJnjDNg3NeutnnqZdMwRRar84dj9/byhsMBMjXhNut85kZLwHSgn/dur/GOC\nBRgMESi08xqyA+wupzSEDZzaWDKSqkHBsJeOCHC3Ji9AOw+CrQpO3XUTAoGBAJXP\nDuid5yrT/jdV1MCJ/E0I2cuZvrGxXDEb8xr95/p30x0GRxlOIq3HjO549/QGrDJ1\nORVnfhi+Pbx1XXibdmiQpZ3Rosb2lVS/0LAAGYEx1qOux83GSZzEriJmanwwpPeq\nFOVLQdSeoaMllE+SZpJfHfCMSEbGwzddVbn0wZAxAoGBAI4D/qgHB4bNdfPV3DSr\nM5z5zAL7HcMoSP8+EJsYpEHV70hl8tbeL4dOT6zDGX+4jRQjbZN5pUbJrOFFDGck\n0uFmtd89Ki7mmrhOJqUXZgG/DTcpp0SrWn9+a1yLjHPnGpbzmRVVoUOQeKoHgnA7\nR3fofD21BLU/n78aVKhHgp6n}}
